# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 743)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.analyzeButton = QtWidgets.QPushButton(self.centralwidget)
        self.analyzeButton.setGeometry(QtCore.QRect(20, 10, 100, 33))
        self.analyzeButton.setStyleSheet("")
        self.analyzeButton.setObjectName("analyzeButton")
        self.textInputPlaceHolder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textInputPlaceHolder.setGeometry(QtCore.QRect(20, 50, 841, 451))
        self.textInputPlaceHolder.setObjectName("textInputPlaceHolder")
        self.textOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.textOutput.setGeometry(QtCore.QRect(20, 510, 841, 181))
        self.textOutput.setReadOnly(True)
        self.textOutput.setObjectName("textOutput")
        self.compileButton = QtWidgets.QPushButton(self.centralwidget)
        self.compileButton.setGeometry(QtCore.QRect(130, 10, 100, 33))
        self.compileButton.setObjectName("compileButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 889, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Compilador"))
        self.analyzeButton.setText(_translate("MainWindow", "  Analisador"))
        self.textOutput.setPlaceholderText(_translate("MainWindow", "Saida"))
        self.compileButton.setText(_translate("MainWindow", "  Compilador  "))
        self.menuFile.setTitle(_translate("MainWindow", "Arquivo"))
        self.actionOpen.setText(_translate("MainWindow", "Abrir"))
        self.actionSave.setText(_translate("MainWindow", "Salvar"))
